config/routes.rb
Rails.application.routes.draw do
  resources :privacy_criteria
  resources :projects
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'projects#index'
  get 'whatisthis' => 'home#wit'
  get 'docen' => "home#doc-en"
  get 'docbr' => "home#doc-br"
  get 'catalog' => "home#catalog"
  get 'case_study' => "home#case_study"
  
  get 'add_share' => "share#add"
  post 'remove_share' => "share#remove"
end

app/views/shared/_footer.html.erb
<div class = "container no-padding footer">
    Icons made by <a href="https://www.flaticon.com/authors/bqlqn" title="bqlqn">bqlqn</a> 
    from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a> is licensed by 
    <a href="http://creativecommons.org/licenses/by/3.0/" title="Creative Commons BY 3.0" target="_blank">CC 3.0 BY</a>
</div>

app/views/shared/_navbar.html.erb
<div class = "container no-padding">
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href=<%= root_path %>>
        <img src=<%=asset_path('cloud-lock.png')%> width="30" height="30" class="d-inline-block align-top" alt="">
        Privacy Criteria
    </a>
    
    <!-- Botão Sanduíche -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    
    <!-- Tudo dentro dessa div vai sumir -->
    <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
      <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
        <li class="nav-item">
          <a class="nav-link" href=<%=whatisthis_path%>>What is this?</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href=<%=docen_path%>>Documentation</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href=<%=catalog_path%>>Catalog</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href=<%=case_study_path%>>Case Study - Example</a>
        </li>
      </ul>
      
      <ul class = "navbar-nav">
        <% if user_signed_in? then%>
          <a class = "nav-link" href=<%= projects_path %>>My Projects</a>
          <a class = "nav-link" href=<%= edit_user_registration_path %>><%= current_user.email.to_s.slice(0,current_user.email.to_s.index('@')) %></a>
          <%= button_to('Sair', destroy_user_session_path, method: :delete, class: "btn btn-danger my-2 my-sm-0") %> 
        <% end %>
        <!-- TODO:
        <li class="nav-item">
            <a class="nav-link" href="#">BR</a>
        </li>
        
        
        <li class="nav-item">
            <a class="nav-link" href="#">EN</a>
  
        </li>
        -->
      </ul>
      
    </div>
</nav>
</div>