config/routes.rb
Rails.application.routes.draw do
  resources :privacy_criteria
  resources :projects
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'projects#index'
  get 'whatisthis' => 'home#wit'
  get 'docen' => "home#doc-en"
  get 'docbr' => "home#doc-br"
  get 'catalog' => "home#catalog"
  get 'case_study' => "home#case_study"
  
  get 'add_share' => "share#add"
  post 'remove_share' => "share#remove"
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  has_many :privacy_criteria, dependent: :destroy
  has_many :share, dependent: :destroy
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.where("user_id = " + current_user.id.to_s)
    shareds = Share.where("user_id = " + current_user.id.to_s)
    
    @shareds = []
    shareds.each do |shar|
      @shareds.push(Project.where("id = " + shar.project_id.to_s)[0])
    end
    
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @privacy_criteria = PrivacyCriterium.where("project_id =" + @project.id.to_s)
    @shareds = Share.where("project_id = " + @project.id.to_s)
    prepare_infos
  end

  # GET /projects/new
  def new
    @project = Project.new
    @project.user_id = current_user.id
  end

  # GET /projects/1/edit
  def edit
    prepare_infos
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      @project.user_id = current_user.id
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:user_id, :name, :description)
    end
    
    def prepare_infos
      shared = Share.where("user_id = " + current_user.id.to_s + "AND project_id = " + @project.id.to_s)
      if (current_user.id != @project.user_id) && (shared.size <= 0) then
        redirect_to root_path
      end
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
    def accessType(string)
        if string == "0" then
            return "Just View"
        else
            return "View and Edit"
        end
    end
end

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.submit class: "btn btn-success" %>
  </div>
<% end %>

app/views/projects/_share.html.erb
<%= form_tag add_share_path, method: :get do%>
    <div class = "form-inline">
        <%= text_field_tag :email, @email, class: "form-control form-control-sm", placeholder: "Type a valid email", style: "margin: 5px 10px 5px 0px;" %>
        <div style = "margin-right: 10px;"><%= radio_button_tag(:access, "0")%> Just View</div>
        <div style = "margin-right: 10px;"><%= radio_button_tag(:access, "1")%> View and Edit</div>
        <%= button_to "Add", nil, params: {project: project}, class: "btn btn-primary btn-sm"%>
    </div>
<% end %>


<table class = "table">
    <thead>
        <tr>
            <th>E-mail</th>
            <th>Access</th>
            <th>Delete</th>
        </tr>
    </thead>
    <tbody>
        <% @shareds.each do |share| %>
            <tr>
                <td><%= User.where('id = ' + share.user_id.to_s)[0].email %></td>
                <td><%= accessType(share.accessa.to_s) %></td>
                <td><%= button_to "Remove", remove_share_path, params:{id: share.id, project: project}%></td>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<p>
  <h1>Projects Dashboard</h1>
  Create a new project to get start!
</p>

<%= button_to 'New Project', new_project_path, method: :get, class: "btn btn-primary" %></br>

<h4>My Projects</h4>

<table class = "table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= link_to project.name, project %></td>
        <td><%= project.description %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Delete', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<hr>

<h4>Shared Projects</h4>

<table class = "table">
  <thead>
    <tr>
      <th>Name</th>
      <td>Description</td>
    </tr>
  </thead>
  <tbody>
    <% @shareds.each do |shar| %>
      <tr>
        <td><%= link_to shar.name, project_path(shar) %></td>
        <td><%= shar.description %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<h4>Project Information</h4>

<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>

<p>
  <strong>Description:</strong></br>
  <%= @project.description %>
</p>

<p>
  <%= link_to 'Edit this Project', edit_project_path(@project) %>
</p>

<hr>

<h4>Sharing Options</h4>
<%= render 'share', project: @project.id %>

<hr>

<h4>Privacy Criterias</h4>
<%= render 'privacy_criteria/index' %></br>
<%= button_to 'New Privacy Criteria', new_privacy_criterium_path, params: {id: @project.id} , class: "btn btn-primary btn-sm", method: :get %>

<p>
  <%= link_to 'Back', projects_path %>
</p>